server:
  port: 8088

spring:
  application:
    name: audit-listener
  datasource:
    url: jdbc:postgresql://localhost:5441/auditDB
    username: root
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

audit:
  kafka:
    bootstrap-servers: localhost:9092

elasticsearch:
  username: elastic
  password: 0=TqZL3DFaqRCizD=39e