server:
  port: 8088

spring:
  application:
    name: audit-listener

audit:
  kafka:
    bootstrap-servers: localhost:9092

elasticsearch:
  username: elastic
  password: 0=TqZL3DFaqRCizD=39e
  recreate-indices: true